services:
  # 🧠 Auth Service
  auth-service:
    build: ../auth-service
    container_name: auth-service
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/authdb
      - JWT_SECRET=supersecretkey # Remplacez par une clé forte en production
      - PORT=5000
    networks:
      - obesity-net

  # 💬 Chat Service
  chat-service:
    build: ../chat-service
    container_name: chat-service
    restart: always
    ports:
      - "5002:5002"
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017/chatdb
      - KAFKA_BROKER=kafka:9092
      - JWT_SECRET=supersecretkey # Identique à auth-service
      - PORT=5002
      - KAFKAJS_NO_PARTITIONER_WARNING=1 # Supprime l'avertissement KafkaJS
    networks:
      - obesity-net

  # 🐘 MongoDB
  mongodb:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - obesity-net

  # 🚀 Kafka avec KRaft mode (sans Zookeeper)
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=obesity-cluster
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - obesity-net

  # 🧭 Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=obesity-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - obesity-net

  # 🌐 Gateway API
  gateway-api:
    build: ../gateway-api
    container_name: gateway-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - chat-service
    networks:
      - obesity-net

# Déclaration des volumes au niveau racine
volumes:
  kafka_data:
  mongo_data:

# Déclaration du réseau
networks:
  obesity-net:
    driver: bridge